"""Synthetic administration fixtures, always marked and reset independently."""
from datetime import datetime, timedelta
from models.admin import AdminUser, AdminRole, UserRole, StudyAccess, AdminStudy, AdminSite, ControlledVersion, IntegrationStatus, AccessReview, AdminAuditEvent
from services.admin_security import ROLE_PERMISSIONS

DEMO_PREFIX = "DEMO-"

def seed_demo(db):
    if db.query(AdminUser).filter(AdminUser.is_demo.is_(True)).first(): return
    now = datetime.utcnow()
    users = [
      AdminUser(id="demo-user-tech", display_name="Tariro Moyo", email="tech.admin.demo@acrnhealth.com", country="Zimbabwe", job_title="Platform Administrator", status="Active", training_status="Current", coi_status="Current", access_expiry=now+timedelta(days=180), last_login=now-timedelta(hours=2), created_by="DEMO-SEED", approved_by="governance.demo@acrnhealth.com", is_demo=True),
      AdminUser(id="demo-user-clinops", display_name="Amara Okafor", email="clinical.ops.demo@acrnhealth.com", country="Nigeria", job_title="Clinical Operations Lead", status="Active", training_status="Current", coi_status="Current", access_expiry=now+timedelta(days=45), last_login=now-timedelta(days=1), created_by="DEMO-SEED", approved_by="qa.demo@acrnhealth.com", is_demo=True),
      AdminUser(id="demo-user-pending", display_name="Lindiwe Dube", email="pending.demo@acrnhealth.com", country="South Africa", organisation="ACRN Partner Site", job_title="Study Coordinator", status="Pending approval", training_status="Incomplete", coi_status="Pending", access_expiry=now+timedelta(days=90), created_by="DEMO-SEED", is_demo=True),
      AdminUser(id="demo-user-auditor", display_name="Kofi Mensah", email="qa.auditor.demo@acrnhealth.com", country="Ghana", job_title="QA Auditor", status="Active", training_status="Current", coi_status="Current", access_expiry=now+timedelta(days=12), last_login=now-timedelta(days=20), created_by="DEMO-SEED", approved_by="governance.demo@acrnhealth.com", is_demo=True),
    ]; db.add_all(users)
    for code, perms in ROLE_PERMISSIONS.items(): db.add(AdminRole(code=code, name=code.replace("_", " ").title(), permissions=sorted(perms), delegated_permissions=sorted(perms), is_demo=True))
    db.add_all([UserRole(user_id="demo-user-tech", role_code="TECHNICAL_ADMIN", assigned_by="DEMO-SEED", reason="Synthetic portal administration", is_demo=True), UserRole(user_id="demo-user-clinops", role_code="CLINICAL_OPS_ADMIN", assigned_by="DEMO-SEED", reason="Synthetic study administration", is_demo=True), UserRole(user_id="demo-user-auditor", role_code="QA_AUDITOR", assigned_by="DEMO-SEED", reason="Synthetic audit role", is_demo=True)])
    db.add_all([
      AdminStudy(id="demo-study-protect", study_code="PROTECT-Africa", version=3, name="PROTECT-Africa EOPE Study", protocol_number="A202501", protocol_version="1.2", endpoint_type="Early-onset pre-eclampsia", countries=["Zimbabwe","South Africa","Ghana"], sponsor="ACRN Foundation", owner="Clinical Operations", status="Active", applicable_sops=["SOP-ADJ-001","SOP-ADJ-002","SOP-ADJ-003","SOP-ADJ-004"], form_versions=["FORM-ADJ-15A v1.0"], mapping_version="MAP-PROTECT-2.1", rule_version="DV-ISSHP-2021-1.0", adjudication_model="Dual blinded independent review", retention_classification="Clinical trial essential record", export_destination="eTMF (placeholder)", environment="DEMO", approved_by="qa.demo@acrnhealth.com", change_reason="Synthetic active configuration", is_demo=True),
      AdminStudy(id="demo-study-lope", study_code="LOPE-Nigeria", version=2, name="LOPE Nigeria", protocol_number="ACRN-202503", protocol_version="1.1", endpoint_type="Late-onset pre-eclampsia", countries=["Nigeria"], sponsor="ACRN Foundation", owner="Clinical Operations", status="Validation", applicable_sops=["SOP-ADJ-001","SOP-ADJ-002"], form_versions=["FORM-ADJ-15B v1.0"], mapping_version="MAP-LOPE-1.1", rule_version="DV-ISSHP-2021-1.0", environment="DEMO", change_reason="Synthetic validation configuration", is_demo=True)
    ])
    db.add_all([AdminSite(site_code="ZWE001", blinded_name="Site ZW-01", country="Zimbabwe", study_code="PROTECT-Africa", status="Active", import_identifier="ZWE001", source_types=["EDC","eSource","LIMS"], contact_reference="CTMS-ZW-01", activation_date=now-timedelta(days=200), is_demo=True), AdminSite(site_code="NGA004", blinded_name="Site NG-04", country="Nigeria", study_code="LOPE-Nigeria", status="Activation pending", import_identifier="NGA004", source_types=["EDC","eSource"], contact_reference="CTMS-NG-04", is_demo=True)])
    for i in range(1,31): db.add(ControlledVersion(resource_type="RULE", code=f"DV-{i:02d}", name=f"DV-{i:02d} controlled clinical derivation", version="1.0", study_codes=["PROTECT-Africa","LOPE-Nigeria"], status="Active", effective_at=now-timedelta(days=120), definition={"purpose":"Deterministic ISSHP-aligned derivation", "inputs":["canonical blinded clinical fields"], "missing_data":"Does not infer missing evidence", "query_conditions":"Configured in authoritative Python engine", "downstream_gates":["evidence review"]}, supporting_reference="ISSHP 2021 / EOPE Working Instruction", test_status="Passed", clinical_approved_by="clinical.demo@acrnhealth.com", qa_approved_by="qa.demo@acrnhealth.com", approved_by="qa.demo@acrnhealth.com", change_reason="Synthetic baseline rule register", is_demo=True))
    db.add_all([
      ControlledVersion(resource_type="MAPPING", code="MAP-PROTECT", name="PROTECT canonical mapping", version="2.1", study_codes=["PROTECT-Africa"], status="Active", definition={"source_system":"EDC/eSource", "source_field":"SYSBP", "canonical_field":"systolic_bp", "data_type":"number", "unit":"mmHg", "required":True, "blinding":"Adjudicator visible"}, test_status="Passed", qa_approved_by="qa.demo@acrnhealth.com", change_reason="Synthetic mapping", is_demo=True),
      ControlledVersion(resource_type="FORM", code="FORM-ADJ-15A", name="EOPE blinded case narrative", version="1.0", study_codes=["PROTECT-Africa"], status="Active", definition={"required_fields":["clinical_timeline","determination","rationale"],"sop":"SOP-ADJ-002"}, test_status="Passed", change_reason="Synthetic form", is_demo=True),
      ControlledVersion(resource_type="WORKFLOW", code="WF-ADJ", name="Adjudication workflow", version="1.0", study_codes=["PROTECT-Africa","LOPE-Nigeria"], status="Active", definition={"states":["Imported","Mapping Review","Pre-QC","QC Released","Assigned","Reviewer In Progress","Reviewer Submitted","Concordance Check","Discordant","Committee Review","Committee Locked","Final QC","Ready for Release","Released","Archived"]}, test_status="Passed", change_reason="Synthetic validated workflow", is_demo=True)
    ])
    for name, typ, status in [("REDCap EDC","EDC","Healthy"),("eSource Adapter","eSource","Warning"),("Laboratory Gateway","LIMS","Healthy"),("Microsoft Entra ID","Identity","Not connected"),("SharePoint","Document","Not connected"),("eTMF Export","eTMF","Warning"),("Notification Service","Notification","Disabled")]: db.add(IntegrationStatus(name=name, integration_type=typ, environment="DEMO", status=status, last_success=now-timedelta(hours=4) if status=="Healthy" else None, last_failure=now-timedelta(days=1) if status=="Warning" else None, last_transfer=now-timedelta(days=1), config_version="1.0", credential_status="Placeholder configured" if status!="Not connected" else "Not configured", enabled=status not in ("Not connected","Disabled"), is_demo=True))
    db.add(AccessReview(name="Q3 2026 Admin Portal Access Review", scope_type="PORTAL", scope_value="ADMIN", reviewer_upn="access.reviewer.demo@acrnhealth.com", status="Open", due_at=now+timedelta(days=14), decisions=[], is_demo=True))
    db.commit()

def reset_demo(db):
    counts = {}
    for model in [AdminAuditEvent, AccessReview, IntegrationStatus, ControlledVersion, AdminSite, StudyAccess, UserRole, AdminRole, AdminStudy, AdminUser]:
        counts[model.__tablename__] = db.query(model).filter(model.is_demo.is_(True)).delete(synchronize_session=False)
    db.commit(); seed_demo(db); return counts

