export const demoUsers = [
 ['Tariro Moyo','tech.admin.demo@acrnhealth.com','Technical Administrator','Platform-wide','Zimbabwe','Current','31 Jan 2027','Active'],
 ['Amara Okafor','clinical.ops.demo@acrnhealth.com','Clinical Operations Administrator','PROTECT-Africa, LOPE-Nigeria','Nigeria','Current','17 Sep 2026','Active'],
 ['Lindiwe Dube','pending.demo@acrnhealth.com','Access requested','PROTECT-Africa','South Africa','Incomplete','Pending','Pending approval'],
 ['Kofi Mensah','qa.auditor.demo@acrnhealth.com','QA/Auditor','All governed studies','Ghana','Current','15 Aug 2026','Active']
]
export const studies=[['PROTECT-Africa','PROTECT-Africa EOPE Study','A202501 v1.2','Zimbabwe, South Africa, Ghana','Active','v3','DV-ISSHP-2021-1.0','MAP-PROTECT-2.1'],['LOPE-Nigeria','LOPE Nigeria','ACRN-202503 v1.1','Nigeria','Validation','v2','DV-ISSHP-2021-1.0','MAP-LOPE-1.1']]
export const sites=[['ZWE001','Site ZW-01','Zimbabwe','PROTECT-Africa','Active','ZWE001','EDC, eSource, LIMS'],['NGA004','Site NG-04','Nigeria','LOPE-Nigeria','Activation pending','NGA004','EDC, eSource']]
export const rules=Array.from({length:30},(_,i)=>[`DV-${String(i+1).padStart(2,'0')}`,'Controlled clinical derivation','ISSHP-aligned deterministic rule','1.0','04 Apr 2026','Active','Clinical + QA','Passed'])
export const mappings=[['EDC / eSource','SYSBP','systolic_bp','Number','mmHg','Required','PROTECT-Africa','2.1','Active','Visible'],['EDC / eSource','DIABP','diastolic_bp','Number','mmHg','Required','PROTECT-Africa','2.1','Active','Visible'],['LIMS','PLT','platelet_count','Number','×10⁹/L','Optional','Both studies','2.1','Active','Visible']]
export const forms=[['FORM-ADJ-01','QC checklist','1.0','Both studies','Active','SOP-ADJ-004'],['FORM-ADJ-05','Data query','1.0','Both studies','Active','SOP-ADJ-004'],['FORM-ADJ-08','Recusal','1.0','Both studies','Active','SOP-ADJ-003'],['FORM-ADJ-09','Unblinding incident','1.0','Both studies','Active','SOP-ADJ-002'],['FORM-ADJ-11','Narrative edit log','1.0','Both studies','Active','SOP-ADJ-004'],['FORM-ADJ-15A','EOPE narrative','1.0','PROTECT-Africa','Active','SOP-ADJ-002'],['FORM-ADJ-15B','LOPE narrative','1.0','LOPE-Nigeria','Active','SOP-ADJ-002']]
export const integrations=[['REDCap EDC','EDC','DEMO','Healthy','Today 06:15','Configured','Enabled'],['eSource Adapter','eSource','DEMO','Warning','02 Aug 2026','Configured','Enabled'],['Laboratory Gateway','LIMS','DEMO','Healthy','Today 05:52','Configured','Enabled'],['Microsoft Entra ID','Identity','DEMO','Not connected','Never','Not configured','Disabled'],['SharePoint','Document','DEMO','Not connected','Never','Not configured','Disabled'],['eTMF Export','eTMF','DEMO','Warning','01 Aug 2026','Placeholder','Enabled']]
export const audits=[['AUD-DEMO-1042','03 Aug 2026 09:18','clinical.ops.demo@acrnhealth.com','CLINICAL_OPS_ADMIN','STUDY_VERSION_CREATED','PROTECT-Africa v3','Protocol alignment','Success'],['AUD-DEMO-1041','03 Aug 2026 08:47','qa.auditor.demo@acrnhealth.com','QA_AUDITOR','MAPPING_APPROVED','MAP-PROTECT 2.1','Validation reviewed','Success'],['AUD-DEMO-1040','02 Aug 2026 16:04','tech.admin.demo@acrnhealth.com','TECHNICAL_ADMIN','ACCESS_REJECTED','pending.demo','Training incomplete','Success'],['AUD-DEMO-1039','02 Aug 2026 14:31','unknown.demo@acrnhealth.com','ADJUDICATOR','ADMIN_ROUTE_DENIED','/api/admin/users','Role not permitted','Failed']]
export const workflow=['Imported','Mapping Review','Reconciliation Required','Packet Preparation','Pre-QC','Query Open','QC Released','Assigned','Reviewer In Progress','Reviewer Submitted','Concordance Check','Discordant','Committee Review','Committee Locked','Final QC','Ready for Release','Released','Archived']
